language: python

python:
      - "3.6"
      - "3.7"
      - "3.8"
      - "3.9"
      - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
    - "pip install --editable .[full]"
    - "pip install -r requirements-build.txt"

script:
    - "flake8"
    - "pytest -v --cov=homography --cov-report=term-missing"

before_deploy:
    - "./build_docs.py"

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
        branch: master
        python: "3.7"

cache:
  apt: true
  pip: true
